# Generated by Django 4.1 on 2022-08-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onecolumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Column image')),
                ('title', models.CharField(max_length=30, verbose_name='Column title')),
                ('text', models.TextField(verbose_name='Column text')),
                ('onecolumnurl', models.URLField(verbose_name='Column url')),
                ('about', models.TextField(verbose_name='Detals')),
            ],
            options={
                'verbose_name': 'Onecolumn',
                'verbose_name_plural': 'Onecolumns',
            },
        ),
        migrations.CreateModel(
            name='Threecolumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Column image')),
                ('title', models.CharField(max_length=30, verbose_name='Column title')),
                ('text', models.TextField(verbose_name='Column text')),
                ('onecolumnurl', models.URLField(verbose_name='Column url')),
                ('about', models.TextField(verbose_name='Detals')),
            ],
            options={
                'verbose_name': 'Threecolumns',
                'verbose_name_plural': 'Threecolumns',
            },
        ),
        migrations.CreateModel(
            name='Twocolumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Column image')),
                ('title', models.CharField(max_length=30, verbose_name='Column title')),
                ('text', models.TextField(verbose_name='Column text')),
                ('onecolumnurl', models.URLField(verbose_name='Column url')),
                ('about', models.TextField(verbose_name='Detals')),
            ],
            options={
                'verbose_name': 'Twocolumns',
                'verbose_name_plural': 'Twocolumns',
            },
        ),
    ]
