# Generated by Django 4.1 on 2022-08-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_onecolumn_threecolumns_twocolumns'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Twocolumns',
            new_name='HomeOnecolumn',
        ),
        migrations.RenameModel(
            old_name='Threecolumns',
            new_name='HomeThreecolumns',
        ),
        migrations.RenameModel(
            old_name='Onecolumn',
            new_name='HomeTwocolumns',
        ),
        migrations.AlterModelOptions(
            name='homeonecolumn',
            options={'verbose_name': 'Onecolumn', 'verbose_name_plural': 'Onecolumns'},
        ),
        migrations.AlterModelOptions(
            name='hometwocolumns',
            options={'verbose_name': 'Twocolumns', 'verbose_name_plural': 'Twocolumns'},
        ),
    ]
