# Generated by Django 4.1 on 2022-08-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_twocolumns_homeonecolumn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeonecolumn',
            options={'verbose_name': 'HomeOnecolumn', 'verbose_name_plural': 'HomeOnecolumns'},
        ),
        migrations.AlterModelOptions(
            name='homethreecolumns',
            options={'verbose_name': 'HomeThreecolumns', 'verbose_name_plural': 'HomeThreecolumns'},
        ),
        migrations.AlterModelOptions(
            name='hometwocolumns',
            options={'verbose_name': 'HomeTwocolumns', 'verbose_name_plural': 'HomeTwocolumns'},
        ),
    ]
