# Generated by Django 4.1 on 2022-08-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_homeonecolumn_text1_homethreecolumns_text1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Category image')),
                ('title', models.CharField(max_length=30, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Product image')),
                ('title', models.CharField(max_length=30, verbose_name='Product name')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Productc',
            },
        ),
    ]
