# Generated by Django 4.1 on 2022-08-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_carmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='imgpng',
            field=models.ImageField(default=1, upload_to='media', verbose_name='ADD image'),
            preserve_default=False,
        ),
    ]
